### ISSUE TITLE
Incompatible with 1.56.2

### ISSUE THREAD

**Issue by adi-works** [oslabs-beta/sapling#94]
**Describe the bug**
Incompatibility with VS Code version `1.56.2`.

**To Reproduce**
Install

**Expected behavior**
Gets Installed

**Screenshots**
![image](https://user-images.githubusercontent.com/12032248/138597532-bf1bdb85-2d42-4bd2-aa0a-2b7010edc6b6.png)

**Desktop (please complete the following information):**
 - OS: `iOS`

**Comment by PLCoster** [comment]
Hi @adi518 ,

Sapling was developed in October 2021 under VS Code version 1.62. Since new features are added to the VS Code extension API as VS Code is updated, the best fix for this problem is to update your version of VS Code to at least version 1.62.

Cheers!

**Comment by adi-works** [comment]
At the time I opened this issue, `v1.56.2` was the latest VS Code version and it didn't work. I'll retry the extension and I'm guessing it will work this time, thanks.
